routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@show')->name('admin');
Route::get('/contact', 'PlaceController@show')->name('contact');

// using resource controller

Route::resource('pizza-sizes', 'PizzaSizeController');
Route::resource('categories', 'CategoryController');
Route::resource('side-dish', 'SideDishController');
Route::resource('side-dish-type', 'SideDishTypeController');
Route::resource('ingredients', 'IngredientController');
Route::resource('pizza', 'PizzaController');


Route::delete('categories/icon/1', 'CategoryController@deleteIcon');

app/Http/Controllers/SideDishController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SideDishRequest;
use App\Model\SideDish;
use App\Model\SideDishType;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;

class SideDishController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('sideDish.SideDishList', ['sideDishCollection' => SideDish::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('sideDish.sideDishCreate', ['dishTypes' => SideDishType::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param SideDishRequest  $sideDish
     * @return \Illuminate\Http\Response
     */
    public function store(SideDishRequest $sideDish)
    {
        DB::table('side_dishes')->insert([
            'side_dish_name' => $sideDish->side_dish_name,
            'side_dish_type_id' => $sideDish->side_dish_type_id,
            'side_dish_volume' => $sideDish->side_dish_volume,
            'side_dish_description' => $sideDish->side_dish_description,
            'side_dish_price' => $sideDish->side_dish_price
        ]);
        return redirect()->route('side-dish.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Model\SideDish  $sideDish
     * @return Collection
     */
    public function show(SideDish $sideDish)
    {
        $sideDishNew = DB::table('side_dishes')
            ->leftJoin('side_dish_types', 'side_dish_type_id', '=', 'side_dish_types.id')
            ->where('side_dishes.id', '=', $sideDish->id)
            ->get();
        return $sideDishNew;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\SideDish  $sideDish
     * @return \Illuminate\Http\Response
     */
    public function edit(SideDish $sideDish)
    {
        $selectedSideDish = $sideDishNew = DB::table('side_dishes')
            ->leftJoin('side_dish_types', 'side_dishes.side_dish_type_id', '=', 'side_dish_types.id')
            ->where('side_dishes.id', '=', $sideDish->id)
            ->select([
                'side_dishes.id',
                'side_dishes.side_dish_name',
                'side_dishes.side_dish_description',
                'side_dishes.side_dish_volume',
                'side_dishes.side_dish_price',
                'side_dish_types.side_dish_type_name',
            ])
            ->first();

        return view('sideDish.sideDishEdit', [
            'sideDish' => $selectedSideDish,
            'dishTypes' => SideDishType::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\SideDishRequest  $request
     * @param  \App\Model\SideDish  $sideDish
     * @return \Illuminate\Http\Response
     */
    public function update(SideDishRequest $request, SideDish $sideDish)
    {
        $sideDish->update([
            'side_dish_name' => $request->side_dish_name,
            'side_dish_type_id' => $request->side_dish_type_id,
            'side_dish_volume' => $request->side_dish_volume,
            'side_dish_description' => $request->side_dish_description,
            'side_dish_price' => $request->side_dish_price
        ]);

        return redirect()->route('side-dish.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\SideDish  $sideDish
     * @return \Illuminate\Http\Response
     */
    public function destroy(SideDish $sideDish)
    {
        try {
            $sideDish->delete();
        } catch (\Exception $exception) {
            return view('sideDish.sideDishEdit', ['errors' => $exception]);
        }
        return redirect()->route('side-dish.index');
    }
}

resources/views/sideDish/SideDishList.blade.php
@extends('layouts.app')
@section('admin-content')
    <div class="col-12">
        <a href="{{ route('side-dish.create') }}">
            <button class="btn btn-primary mb-3"><i class="fa fa-plus"></i> Add new</button>
        </a>
        <table class="table">
            @foreach($sideDishCollection->sortBy('side_dish_type_id')->groupBy('side_dish_type_id') as $collection)
                <tr>
                    <td colspan="6">
                        <h3>
                            {{ $collection[0]->sideDishType->side_dish_type_name}}
                        </h3>
                    </td>
                </tr>
                <tr class="alert-primary">
                    <td>Name</td>
                    <td>Volume</td>
                    <td>Description</td>
                    <td>Price</td>
                    <td></td>
                    <td></td>
                </tr>

                    @foreach($collection->sortBy('side_dish_name') as $dish)
                    <tr>
                        <td>
                            {{ $dish->side_dish_name }}
                        </td>
                        <td>
                            {{ $dish->side_dish_volume }}
                        </td>
                        <td>
                            {{ $dish->side_dish_description }}
                        </td>
                        <td>
                            {{ $dish->side_dish_price }}
                        </td>
                        <td>
                            <a href="{{ route('side-dish.edit', ['id' => $dish->id]) }}">
                                <button class="btn btn-success">
                                    <i class="fa fa-pencil"></i>
                                </button>
                            </a>
                        </td>
                        <td>
                            <form method="POST" action="{{ route('side-dish.destroy', ['id' => $dish->id]) }}">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach

            @endforeach
        </table>

    </div>

@endsection

resources/views/sideDish/sideDishCreate.blade.php
@extends('layouts.app')
@section('admin-content')
    <div class="col-12">
        <h2>Add side dish</h2>
        <form action="{{route('side-dish.store')}}" class="row" method="POST">
            @csrf
            <div class="form-group col-12 row">
                <label for="side_dish_name" class="col-3 mt-2">Side dish name:</label>
                <input type="text" id="side_dish_name" name="side_dish_name" class="col-6 form-control">
            </div>
            <div class="form-group col-12 row">
                <label for="side_dish_type_id" class="col-3 mt-2">Side dish type:</label>
                <select class="form-control col-6" id="side_dish_type_id" name="side_dish_type_id">
                    @foreach($dishTypes as $dishType)
                        <option value="{{ $dishType->id }}">{{ $dishType->side_dish_type_name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group col-12 row">
                <label for="side_dish_volume" class="col-3 mt-2">Side dish volume:</label>
                <input type="text" id="side_dish_volume" name="side_dish_volume" class="col-6 form-control">
            </div>
            <div class="form-group col-12 row">
                <label for="side_dish_description" class="col-3 mt-2">Side dish description:</label>
                <textarea type="text" id="side_dish_description" name="side_dish_description" class="col-6 form-control"></textarea>
            </div>
            <div class="form-group col-12 row">
                <label for="side_dish_price" class="col-3 mt-2">Side dish price:</label>
                <input type="text" id="side_dish_price" name="side_dish_price" class="col-6 form-control">
            </div>
            @include('errors.form-error')
            <div class="form-group col-12 row">
                <button class="btn btn-primary offset-8">Submit</button>
            </div>

        </form>
    </div>
@endsection

resources/views/sideDish/sideDishEdit.blade.php
@extends('layouts.app')
@section('admin-content')
    <div class="col-12">
        {{ $sideDish->id }}
        <h2>Add side dish</h2>
        <form action="{{ route('side-dish.update', ['id' => $sideDish->id]) }}" class="row" method="POST">
            @csrf
            @method('PUT')
            <div class="form-group col-12 row">
                <label for="side_dish_name" class="col-3 mt-2">Side dish name:</label>
                <input type="text" id="side_dish_name" value="{{ $sideDish->side_dish_name }}" name="side_dish_name" class="col-6 form-control">
            </div>
            <div class="form-group col-12 row">
                <label for="side_dish_type_id" class="col-3 mt-2">Side dish type:</label>
                <select class="form-control col-6" id="side_dish_type_id" name="side_dish_type_id">
                    @foreach($dishTypes as $dishType)
                        <option value="{{ $dishType->id }}"
                        @if($dishType->side_dish_type_name == $sideDish->side_dish_type_name)
                            selected="selected"
                        @endif
                        >{{ $dishType->side_dish_type_name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group col-12 row">
                <label for="side_dish_volume" class="col-3 mt-2">Side dish volume:</label>
                <input type="text" id="side_dish_volume" value="{{ $sideDish->side_dish_volume }}" name="side_dish_volume" class="col-6 form-control">
            </div>
            <div class="form-group col-12 row">
                <label for="side_dish_description" class="col-3 mt-2">Side dish description:</label>
                <textarea type="text" id="side_dish_description" name="side_dish_description" class="col-6 form-control">{{ $sideDish->side_dish_description }}</textarea>
            </div>
            <div class="form-group col-12 row">
                <label for="side_dish_price" class="col-3 mt-2">Side dish price:</label>
                <input type="text" id="side_dish_price" value="{{ $sideDish->side_dish_price }}" name="side_dish_price" class="col-6 form-control">
            </div>
            @include('errors.form-error')
            <div class="form-group col-12 row">
                <button class="btn btn-primary offset-8">Submit</button>
            </div>

        </form>
    </div>
@endsection

resources/views/sideDish/sideDishTypeEdit.blade.php
@extends('layouts.app')
@section('admin-content')
    <div class="col-12">
        <form action="{{ route('side-dish-type.update', ['id' => $sideDishType->id]) }}" class="row" method="POST">
            @csrf
            @method('PUT')
            <div class="form-group col-12 row">
                <label for="side_dish_type_name" class="col-3 mt-2">Type name:</label>
                <input type="text" class="form-control col-6" id="side_dish_type_name" name="side_dish_type_name" value="{{ $sideDishType->side_dish_type_name }}">
            </div>
            @include('errors.form-error')
            <div class="form-group col-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
@endsection

resources/views/sideDish/sideDishTypeList.blade.php
@extends('layouts.app')
@section('admin-content')

    <div class="col-12">
        <h1>Side dish types</h1>
    </div>

    <div class="col-12">
        @foreach($sideDishTypes as $sideDishType)
            <a href="{{ route('side-dish-type.edit', ['id' => $sideDishType->id]) }}">
                <button class="btn btn-default">{{ $sideDishType->side_dish_type_name }}
                    <form action="{{ route('side-dish-type.destroy', ['id' => $sideDishType->id]) }}" method="POST">
                        @csrf
                        @method('delete')
                        <button type="submit" class="button btn btn-danger"><i class="fa fa-trash"></i></button>
                    </form>

                </button>
            </a>
        @endforeach
    </div>
    <div class="col-12 mt-4">
        <form action="{{ route('side-dish-type.store') }}" class="col-12 row" method="POST">
            @csrf
            <div class="form-group col-12 row">
                <label for="type_name" class="col-3 mt-2">Type name:</label>
                <input type="text" class="form-control col-6" id="type_name" name="side_dish_type_name">
            </div>
            @include('errors.form-error')
            <div class="form-group col-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>

@endsection