routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@show')->name('admin');
Route::get('/contact', 'PlaceController@show')->name('contact');

// using resource controller

Route::resource('pizza-sizes', 'PizzaSizeController');
Route::resource('categories', 'CategoryController');
Route::resource('side-dish', 'SideDishController');
Route::resource('side-dish-type', 'SideDishTypeController');
Route::resource('ingredients', 'IngredientController');
Route::resource('pizza', 'PizzaController');


Route::delete('categories/icon/1', 'CategoryController@deleteIcon');

app/Http/Controllers/IngredientController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\IngredientRequest;
use App\Model\Ingredient;
use App\Model\PizzaSize;

class IngredientController extends Controller
{
    /**
     * Display a listing of the ingredients.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('ingredients.ingredientList', [
            'ingredients' => Ingredient::all(),
            'sizes' => PizzaSize::all()
        ]);
    }

    /**
     * Show the form for creating a new ingredient.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('ingredients.ingredientCreate', [ 'pizzaSizes' => PizzaSize::all() ]);
    }

    /**
     * Store a newly created ingredient in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(IngredientRequest $request)
    {
        $ingredientPrices = $request->except([
            '_token', 'ingredient_name', 'ingredient_description'
        ]);
        $ingredient = new Ingredient();
        $ingredient->ingredient_name = $request->ingredient_name;
        $ingredient->ingredient_description = $request->ingredient_description;
        $ingredient->save();

        /**
         * This loop is inserting data to pivot table with prices.
         * Field name can't be a number, so we are using SIZE_PREFIX in blade
         * files and then remove it here.
         *
         * @var integer $ingredientPrice
         * @var string $key
         */
        foreach ($ingredientPrices as $key => $ingredientPrice) {
            $ingredientPriceId = str_replace('size_', '', $key);
            $ingredient
                ->pizzaSizes()
                ->attach($ingredientPriceId, [
                    'ingredient_size_price' =>$ingredientPrice
                ]);
        }

        return redirect()
            ->route('ingredients.index')
            ->with('success', 'Ingredient was created correctly.');
    }

    /**
     * Display the specified ingredient.
     *
     * @param  \App\Model\Ingredient  $ingredient
     * @return \App\Model\Ingredient  $ingredient
     */
    public function show(Ingredient $ingredient)
    {
        return $ingredient->pizzaSizes;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Model\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function edit(Ingredient $ingredient)
    {
        return view('ingredients.ingredientEdit', [
            'ingredient' => $ingredient,
            'pizzaSizes' => PizzaSize::all()
        ]);
    }

    /**
     * Update the specified ingredient in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Model\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function update(IngredientRequest $request, Ingredient $ingredient)
    {
        // TODO: it could be an array, not multiple request position. REDO!!
        $pizzaSizePrices = $request->except([
            '_token', '_method', 'ingredient_name', 'ingredient_description', 'id'
        ]);

        $ingredient->update([
            'ingredient_name' => $request->ingredient_name,
            'ingredient_description' => $request->ingredient_description
        ]);

        /**
         * When modifying ingredient, it's new prices should change in pivot
         *
         * @var string $key
         * @var integer $pizzaSizePrice
         */
        foreach ($pizzaSizePrices as $key => $pizzaSizePrice) {
            $pizzaSizeKey = str_replace('size_', '', $key);
            $ingredient
                ->pizzaSizes()
                ->syncWithoutDetaching([
                    $pizzaSizeKey => ['ingredient_size_price' => $pizzaSizePrice]
                ]);
        }

        return redirect()
            ->route('ingredients.index')
            ->with('success', 'Ingredient was updated correctly.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Model\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function destroy(Ingredient $ingredient)
    {
        $ingredient->pizzaSizes()->detach();

        try {
            $ingredient->delete();
        } catch (\Exception $exception) {
            return view('ingredients.ingredientList')
                ->withErrors(['errors.delete' => 'Something went wrong!']);
        }

        return redirect()
            ->route('ingredients.index')
            ->with('success', 'Ingredient was deleted correctly.');
    }
}

resources/views/ingredients/ingredientCreate.blade.php
@extends('layouts.app')
@section('admin-content')
    <div class="col-12">
        <h1>Create new ingredients</h1>
        <form action="{{ route('ingredients.store') }}" method="POST" class="row container-fluid col-12">
            @csrf
            <div class="row form-group col-12">
                <label for="ingredient_name" class="col-3 mt-2">Ingredient name</label>
                <input type="text" id="ingredient_name" name="ingredient_name" class="col-8 form-control">
            </div>
            <div class="row form-group col-12">
                <label for="ingredient_description" class="col-3 mt-2">Ingredient description</label>
                <textarea id="ingredient_description" name="ingredient_description" class="col-8 form-control"></textarea>
            </div>
            <div class="row form-group col-12">
                <h3>Prices for sizes</h3>
                @foreach($pizzaSizes as $pizzaSize)
                <div class="col-12 form-group row">
                    <label for="size_{{ $pizzaSize->id }}" class="col-2 mt-2">
                        {{ $pizzaSize->size_name }}:
                    </label>
                    <input
                            type="text" name="size_{{ $pizzaSize->id }}"
                            id="size_{{ $pizzaSize->id }}"
                            class="col-2 form-control" value="0">
                </div>
                @endforeach
            </div>
            @include('errors.form-error')
            <div class="col-12">
                <button class="btn btn-primary col-4">
                    Submit
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/ingredients/ingredientEdit.blade.php
@extends('layouts.app')
@section('admin-content')
    <div class="col-12">
        <h1>Create new ingredients</h1>
        <form action="{{ route('ingredients.update', [ 'id' => $ingredient->id ]) }}" method="POST" class="row container-fluid col-12">
            @csrf
            @method('PUT')

            <input type="hidden" value="{{ $ingredient->id }}" name="id">
            <div class="row form-group col-12">
                <label for="ingredient_name" class="col-3 mt-2">Ingredient name</label>
                <input type="text"
                       id="ingredient_name"
                       name="ingredient_name"
                       class="col-8 form-control"
                       value="{{ $ingredient->ingredient_name }}"
                >
            </div>
            <div class="row form-group col-12">
                <label for="ingredient_description" class="col-3 mt-2">Ingredient description</label>
                <textarea
                       id="ingredient_description"
                       name="ingredient_description"
                       class="col-8 form-control"
                >{{ $ingredient->ingredient_description }}</textarea>
            </div>
            <div class="row form-group col-12">
                <h3>Prices for sizes</h3>

                @foreach($pizzaSizes as $key => $pizzaSize)
                    <div class="col-12 form-group row">
                        <label for="size_{{ $pizzaSize->id }}" class="col-2 mt-2">
                            {{ $pizzaSize->size_name }}:
                        </label>
                        <input
                                type="text" name="size_{{ $pizzaSize->id }}"
                                id="size_{{ $pizzaSize->id }}"
                                class="col-2 form-control" value="{{ $ingredient->pizzaSizes[$key]->pivot->ingredient_size_price }}">
                    </div>
                @endforeach

            </div>

            @include('errors.form-error')

            <div class="col-12">
                <button class="btn btn-primary col-4">
                    Submit
                </button>
            </div>
        </form>
    </div>
@endsection

resources/views/ingredients/ingredientList.blade.php
@extends('layouts.app')

@section('admin-content')
    @include('success.show')
    <div class="col-12">
        <a href="{{ route('ingredients.create') }}">
            <button class="btn btn-primary mb-3"><i class="fa fa-plus"></i> Add new</button>
        </a>
            <table class="table">
                <thead>
                    <tr>
                        <th rowspan="2">Ingredient name</th>
                        <th rowspan="2">Ingredient description</th>
                        <th colspan="{{ $sizes->count() }}">Prices</th>
                        <th rowspan="2"></th>
                        <th rowspan="2"></th>
                    </tr>
                    <tr>
                        @foreach($sizes as $size)
                            <th class="text-center">{{ $size->size_name }}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody>
                    @foreach($ingredients->sortBy('ingredient_name') as $ingredient)
                        <tr>
                            <td>{{ $ingredient->ingredient_name }}</td>
                            <td>{{ $ingredient->ingredient_description }}</td>
                                @foreach($ingredient->pizzaSizes as $pizzaSize)
                                    <td class="text-center">
                                        {{ $pizzaSize->pivot->ingredient_size_price }}
                                    </td>
                                @endforeach
                            <td class="p-0">
                                <a href="{{ route('ingredients.edit', [ 'id' => $ingredient->id ]) }}">
                                    <button class="btn btn-success w-100 mt-1">
                                        <i class="fa fa-pencil"></i>
                                    </button>
                                </a>
                            </td>
                            <td class="p-0">
                                <form action="{{ route('ingredients.destroy', [ 'id' => $ingredient->id ]) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger w-100 mt-1">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
@endsection