routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/admin', 'AdminController@show')->name('admin');
Route::get('/contact', 'PlaceController@show')->name('contact');

// using resource controller

Route::resource('pizza-sizes', 'PizzaSizeController');
Route::resource('categories', 'CategoryController');
Route::resource('side-dish', 'SideDishController');
Route::resource('side-dish-type', 'SideDishTypeController');
Route::resource('ingredients', 'IngredientController');
Route::resource('pizza', 'PizzaController');


Route::delete('categories/icon/1', 'CategoryController@deleteIcon');

app/Http/Controllers/PizzaController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PizzaRequest;
use App\Model\Category;
use App\Model\Ingredient;
use App\Model\Pizza;
use App\Model\PizzaSize;

class PizzaController extends Controller
{
    /**
     * Display a listing of the pizza.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pizza.pizzaList', [
            'pizzas' => Pizza::all()
        ]);
    }

    /**
     * Show the form for creating a new pizza.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pizza.pizzaCreate', [
            'pizzaSizes' => PizzaSize::all(),
            'ingredients' => Ingredient::all(),
            'categories' => Category::all()
        ]);
    }

    /**
     * Store a newly created pizza in storage.
     *
     * @param  \App\Http\Requests\PizzaRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PizzaRequest $request)
    {
        $pizza = new Pizza();
        $pizza->pizza_name = $request->pizza_name;
        $pizza->pizza_description = $request->pizza_description;
        $pizza->pizza_spiciness = $request->pizza_spiciness;
        $pizza->category_id = $request->pizza_category;
        $pizza->save();

        /**
         * sending table to attach relation to pivot.
         */
        $pizza
            ->ingredients()
            ->attach($request->all()['ingredients']);

        /**
         * Sening prices to pivot. There is a price in pivot tablel, so we need to attach value to proper key.
         *
         * @var int $key
         * @var number $price
         */
        foreach ($request->all()['pizza_price'] as $key => $price) {
            $pizza
                ->pizzaSizes()
                ->attach($key, [
                    'pizza_size_price' => $price
                ]);
        }

        return redirect()
            ->route('pizza.index')
            ->with('success', 'New pizza added in ' . $pizza->category->category_name . ' category.');
    }

    /**
     * Display the specified pizza.
     *
     * @param  \App\Model\Pizza  $pizza
     * @return Pizza $pizza
     */
    public function show(Pizza $pizza)
    {
        //
    }

    /**
     * Show the form for editing the specified pizza.
     *
     * @param  \App\Model\Pizza  $pizza
     * @return \Illuminate\Http\Response
     */
    public function edit(Pizza $pizza)
    {
        return view('pizza.pizzaEdit', [
            'pizza' => $pizza,
            'ingredients' => Ingredient::all(),
            'categories' => Category::all()
            ]);
    }

    /**
     * Update the specified pizza in storage.
     *
     * @param  \App\Http\Requests\PizzaRequest  $request
     * @param  \App\Model\Pizza  $pizza
     * @return \Illuminate\Http\Response
     */
    public function update(PizzaRequest $request, Pizza $pizza)
    {
        $pizza->update([
            'pizza_name' => $request->pizza_name,
            'pizza_description' => $request->pizza_description,
            'pizza_spiciness' => $request->pizza_spiciness,
            'category_id' => $request->pizza_category
        ]);

        /**
         * As we have pivot with value, we have to sync like this. All prices are required, so we are using syncWithoutDetaching.
         *
         * @var int $key
         * @var number $price
         */
        foreach ($request->all()['pizza_price'] as $key => $price) {
            $pizza
                ->pizzaSizes()
                ->syncWithoutDetaching([
                    $key => [
                        'pizza_size_price' => $price
                    ]
                ]);
        }

        /**
         * we are sending a table of ingredients' ids to sync in pivot.
         */
        $pizza
            ->ingredients()
            ->sync($request->all()['ingredients']);

        return redirect()
            ->route('pizza.index')
            ->with('success', 'Pizza ' . $pizza->pizza_name . ' was modify!');
    }

    /**
     * Remove the specified pizza from storage.
     *
     * @param  \App\Model\Pizza  $pizza
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pizza $pizza)
    {
        $pizza->ingredients()->detach();
        $pizza->pizzaSizes()->detach();

        try {
            $pizza->delete();
        } catch (\Exception $exception) {
            return view('ingredients.ingredientList')
                ->withErrors(['errors.delete' => 'Something went wrong!']);
        }

        return redirect()
            ->route('pizza.index')
            ->with('success', 'Pizza was deleted correctly.');
    }
}

resources/views/pizza/pizzaCreate.blade.php
@extends('layouts.app')
@section('admin-content')
    @include('errors.form-error')
    {{-- TODO: Add prices for pizza--}}
    <div class="col-12 mb-2">
        <h1>Add pizza</h1>
    </div>
    <div class="col-12">
        <form action="{{ route('pizza.store') }}" method="POST">
            @csrf
            <div class="row form-group col-12">
                <label
                        class="col-2 mt-2"
                        for="pizza_name">
                    Pizza name:
                </label>
                <input
                        type="text"
                        class="col-9 form-control"
                        name="pizza_name"
                        id="pizza_name">
            </div>
            <div class="row form-group col-12">
                <label
                        class="col-2 mt-2"
                        for="pizza_description">
                    Pizza description:
                </label>
                <textarea
                        type="text"
                        class="col-9 form-control"
                        name="pizza_description"
                        id="pizza_description"></textarea>
            </div>
            <div class="row form-group col-12">
                <label
                        class="col-2 mt-2"
                        for="pizza_spiciness">
                    Pizza spiciness:
                </label>
                <select class="col-2 form-control text-danger" name="pizza_spiciness" id="pizza_spiciness">
                    <option selected value="0" class="alert-primary">0</option>
                    <option value="1" class="alert-success">1</option>
                    <option value="2" class="alert-warning">2</option>
                    <option value="3" class="alert-danger">3</option>
                </select>
            </div>
            @foreach(\App\Model\PizzaSize::all() as $size)
                <div class="row form-group col-12">
                        <label
                                class="col-3 mt-2"
                                for="pizza_price[{{ $size->id }}]">
                            {{ title_case($size->size_name) }} pizza price:
                        </label>
                        <input
                                type="text"
                                class="col-1 form-control"
                                name="pizza_price[{{ $size->id }}]"
                                id="pizza_price[{{ $size->id }}]">
                </div>
            @endforeach
            <div class="row form-group col-12">
                <label
                        class="col-2 mt-2"
                        for="pizza_category">
                    Pizza category:
                </label>
                <select
                        class="col-5 form-control"
                        name="pizza_category"
                        id="pizza_category">
                    <option selected disabled>choose category</option>

                    @foreach($categories->sortBy('category_name') as $category)
                        <option value="{{ $category->id }}">{{ $category->category_name }}</option>
                    @endforeach

                </select>
            </div>
            <div class="row form-group col-12">

                @foreach($ingredients as $ingredient)
                    <label for="{{ $ingredient->id }}" class="form-check-label">
                        <div class="alert alert-primary m-1 form-check form-check-inline">
                            {{ $ingredient->ingredient_name }}
                            <input
                                    type="checkbox"
                                    class="ml-2 form-check-input"
                                    name="ingredients[]"
                                    id="{{ $ingredient->id }}"
                                    value="{{ $ingredient->id }}"
                                    @if($ingredient->id === 7 || $ingredient->id === 6)
                                            checked
                                    @endif
                            >
                        </div>
                    </label>
                @endforeach

            </div>
            <div class="col-12">
                <button class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
@endsection

resources/views/pizza/pizzaEdit.blade.php
@extends('layouts.app')
@section('admin-content')
    @include('errors.form-error')
    <div class="col-12 mb-2">
        <h1>Add pizza</h1>
    </div>
    <div class="col-12">
        <form action="{{ route('pizza.update', [ 'id' => $pizza->id ]) }}" method="POST">
            @csrf
            @method('PUT')

            <input type="hidden" value="{{ $pizza->id }}" id="id" name="id">
            <div class="row form-group col-12">
                <label
                        class="col-2 mt-2"
                        for="pizza_name">
                    Pizza name:
                </label>
                <input
                        type="text"
                        class="col-9 form-control"
                        name="pizza_name"
                        id="pizza_name"
                        value="{{ $pizza->pizza_name }}">
            </div>
            <div class="row form-group col-12">
                <label
                        class="col-2 mt-2"
                        for="pizza_description">
                    Pizza description:
                </label>
                <textarea
                        type="text"
                        class="col-9 form-control"
                        name="pizza_description"
                        id="pizza_description">{{ $pizza->pizza_description }}</textarea>
            </div>
            <div class="row form-group col-12">
                <label
                        class="col-2 mt-2"
                        for="pizza_spiciness">
                    Pizza spiciness:
                </label>
                <select class="col-2 form-control" name="pizza_spiciness" id="pizza_spiciness">
                    @for($spiciness = 0; $spiciness <= 3; $spiciness++)
                        <option value="{{ $spiciness }}"
                        @if($spiciness == $pizza->pizza_spiciness)
                            selected
                        @endif
                        >{{ $spiciness }}</option>
                    @endfor
                </select>
            </div>

            @foreach($pizza->pizzaSizes as $size)
                <div class="row form-group col-12">
                    <label
                            class="col-3 mt-2"
                            for="pizza_price[{{ $size->id }}]">
                        {{ title_case($size->size_name) }} pizza price:
                    </label>
                    <input
                            type="text"
                            class="col-1 form-control"
                            name="pizza_price[{{ $size->id }}]"
                            id="pizza_price[{{ $size->id }}]"
                            value="{{ $size->pivot->pizza_size_price }}">
                </div>
            @endforeach

            <div class="row form-group col-12">
                <label
                        class="col-2 mt-2"
                        for="pizza_category">
                    Pizza category:
                </label>
                <select
                        class="col-5 form-control"
                        name="pizza_category"
                        id="pizza_category">

                    @foreach($categories->sortBy('category_name') as $category)
                        <option value="{{ $category->id }}"

                                @if($category->id === $pizza->category->id)
                                    selected
                                @endif

                        >{{ $category->category_name }}</option>
                    @endforeach

                </select>
            </div>
            <div class="row form-group col-12">

                @foreach($ingredients as $ingredient)
                    <label for="{{ $ingredient->id }}" class="form-check-label">
                        <div class="alert alert-primary m-1 form-check form-check-inline">
                            {{ $ingredient->ingredient_name }}
                            <input
                                    type="checkbox"
                                    class="ml-2 form-check-input"
                                    name="ingredients[]"
                                    id="{{ $ingredient->id }}"
                                    value="{{ $ingredient->id }}"
                                    @if($pizza->checkCorrectIngredients($ingredient->id))
                                        checked
                                    @endif
                            >
                        </div>
                    </label>
                @endforeach

            </div>
            <div class="col-12">
                <button class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
@endsection

resources/views/pizza/pizzaList.blade.php
@extends('layouts.app')
@section('admin-content')
    @include('success.show')
    <div class="col-12 mb-2">
        <a href="{{ route('pizza.create') }}">
            <button class="btn btn-primary"><i class="fa fa-plus"></i> Add new</button>
        </a>
    </div>
    <div class="col-12">
        <h1>Pizzas</h1>
        <table class="table table-borderless">
                <thead class="border-bottom">
                <tr>
                    <th rowspan="2">Pizza name</th>
                    <th rowspan="2">Pizza description</th>
                    <th colspan="{{ $pizzas[0]->pizzaSizes->count() }}">Prices</th>
                    <th rowspan="2"></th>
                    <th rowspan="2"></th>
                </tr>
                <tr>
                    @foreach($pizzas[0]->pizzaSizes as $size)
                        <th class="text-center">{{ $size->size_name }}</th>
                    @endforeach
                </tr>
                </thead>
            <tbody>
            @foreach($pizzas->sortByDesc('category_id')->groupBy('category_id') as $sortedPizzas)
                <tr>
                    <td colspan="7">
                        <h5 class="alert alert-primary">
                            Category: {{ $sortedPizzas[0]->category->category_name }}
                        </h5>
                    </td>
                </tr>
                @foreach($sortedPizzas as $pizza)
                    <tr>
                        <td>
                            <div class="container-fluid row col-12">
                                <div class="d-block col-8">{{ $pizza->pizza_name }}</div>
                                <div class="col-4">
                                    @for($i = 0; $i < $pizza->pizza_spiciness; $i++)
                                        <i class="em em-hot_pepper" style="font-size: 0.6rem;"></i>
                                    @endfor
                                </div>
                            </div>
                        </td>
                        <td>
                            {{ $pizza->pizza_description }}
                        </td>
                        @foreach($pizza->pizzaSizes as $size)
                            <td class="text-center">{{ $size->pivot->pizza_size_price }}</td>
                        @endforeach
                        <td>
                            <a href="{{ route('pizza.edit', [ 'id' => $pizza->id ]) }}">
                                <button class="btn btn-success w-100 mt-1">
                                    <i class="fa fa-pencil"></i>
                                </button>
                            </a>
                        </td>
                        <td>
                            <form action="{{ route('pizza.destroy', [ 'id' => $pizza->id ]) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger w-100 mt-1">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    <tr class="border-bottom">
                        <td colspan="7">
                            @foreach($pizza->ingredients as $ingredient)
                                <span class="p-2">
                                    <i class="fa fa-crosshairs text-success"></i> {{ $ingredient->ingredient_name }},
                                </span>
                            @endforeach
                        </td>
                    </tr>
                @endforeach

            @endforeach
            </tbody>
        </table>
    </div>
@endsection